feat: Update chart to support upstream images
hashgraph/hedera-sourcify pull request #171
Opened 2024-05-22 15:23 UTC by beeradb

This PR updates the sourcify chart with changes to support using upstream images. The changes are as follows:

- add servers.yaml, sourcify-chains.json, and local.js as Configmaps and mount them to the server container.
- Rework container image structure in both values.yaml and the corresponding deployments.
- Some minor linting of trailing spaces & newlines.

2024-05-23 15:48 UTC, acuarica requested changes
lgtm thanks for taking care of this.

I left some improvements I didn't mention before.

2024-05-23 15:48 UTC, acuarica commented on charts/values.yaml
> +        }
For integration and production this network should be removed.

2024-05-23 15:48 UTC, acuarica commented on charts/templates/server-repository/configmap.yaml
> +          process.env.NODE_ENV !== "production" && /^https?:\/\/localhost(?::\d+)?$/, // localhost on any port /^{{ .Values.serverRepository.config.SERVER_URL }}$/
also this one

2024-05-23 15:48 UTC, acuarica commented on charts/templates/server-repository/configmap.yaml
>    UI_DOMAIN_NAME: {{ .Values.serverRepository.config.UI_DOMAIN_NAME }}
Can we delete `TESTING`, `UI_DOMAIN_NAME` and `REPOSITORY_PATH`?

Can we change the default of `NODE_ENV` to `production`?

2024-05-24 13:59 UTC, acuarica commented on charts/templates/server-repository/deployment.yaml
> +          image: "{{ .Values.serverRepository.image.server.repository }}:{{ .Values.serverRepository.image.server.tag | default "server-latest" }}"
Same with `ui` image name.

2024-05-24 14:15 UTC, acuarica commented on charts/templates/server-repository/configmap.yaml
>    REPOSITORY_SERVER_EXTERNAL_PORT: {{ .Values.serverRepository.service.repository.port | quote }}
These `*_PORT` config should also be removed, they are not used by any application.

2024-06-05 15:25 UTC, acuarica submitted a review, later dismissed
lgtm

2024-06-05 19:14 UTC, acuarica approved these changes
lgtm

2024-06-05 20:01 UTC, jeromy-cannon approved these changes

2024-06-06 19:39 UTC, merged